name: Cppcheck Static Analysis
on: [push, pull_request]

jobs:
  cppcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Cppcheck & Python Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cppcheck python3

      - name: Run MISRA Compliance Scan
        run: |
          cppcheck --enable=all --addon=misra.json --suppress=*:*Drivers/* --suppress=*_hal_msp.c --suppress=*_it.c --suppress=syscalls.c --suppress=sysmem.c --suppress=system_*.c --suppress=missingInclude --suppress=missingIncludeSystem Core/Src/
