name: Cppcheck Static Analysis
on: [push, pull_request]

jobs:
  cppcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Cppcheck
        run: |
          sudo apt-get update
          sudo apt-get install -y cppcheck python3

      - name: Run MISRA Compliance Scan
        run: |
          cppcheck --enable=all \
            --error-exitcode=0 \
            --addon=misra.json \
            --addon-python=python3 \
            --suppress=*:*Drivers/* \
            --suppress=*:*Core/Src/stm32f4xx_* \
            --suppress=*:*Core/Src/sys* \
            --suppress=missingInclude \
            --suppress=missingIncludeSystem \
            --suppress=unusedFunction \
            Core/Src/
